"""Add relationships to Asset

Revision ID: 5508a66f37a7
Revises: 
Create Date: 2024-08-11 12:49:59.196644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5508a66f37a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_status',
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_status'),
    sa.UniqueConstraint('status_name')
    )
    op.create_table('asset_type',
    sa.Column('id_asset_type', sa.Integer(), nullable=False),
    sa.Column('asset_type_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_asset_type'),
    sa.UniqueConstraint('asset_type_name')
    )
    op.create_table('client',
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('client_email', sa.String(length=100), nullable=False),
    sa.Column('client_phone', sa.String(length=20), nullable=False),
    sa.Column('client_address', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_client'),
    sa.UniqueConstraint('client_email')
    )
    op.create_table('reservation_status',
    sa.Column('id_reservation_status', sa.Integer(), nullable=False),
    sa.Column('reservation_status_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_reservation_status'),
    sa.UniqueConstraint('reservation_status_name')
    )
    op.create_table('status',
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_status'),
    sa.UniqueConstraint('status_name')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('surname', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('interior_number', sa.String(length=10), nullable=True),
    sa.Column('exterior_number', sa.String(length=10), nullable=True),
    sa.Column('municipality', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('profile', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('enterprise',
    sa.Column('id_enterprise', sa.Integer(), nullable=False),
    sa.Column('enterprise_name', sa.String(length=80), nullable=False),
    sa.Column('enterprise_rfc', sa.String(length=50), nullable=True),
    sa.Column('enterprise_phone', sa.String(length=20), nullable=True),
    sa.Column('enterprise_email', sa.String(length=100), nullable=True),
    sa.Column('enterprise_contact_name', sa.String(length=100), nullable=True),
    sa.Column('enterprise_fiscal_name', sa.String(length=100), nullable=True),
    sa.Column('enterprise_fiscal_street', sa.String(length=100), nullable=True),
    sa.Column('enterprise_fiscal_internal_number', sa.String(length=20), nullable=True),
    sa.Column('enterprise_fiscal_external_number', sa.String(length=20), nullable=True),
    sa.Column('enterprise_fiscal_municipio', sa.String(length=100), nullable=True),
    sa.Column('enterprise_fiscal_state', sa.String(length=100), nullable=True),
    sa.Column('enterprise_fiscal_country', sa.String(length=100), nullable=True),
    sa.Column('enterprise_fiscal_postal_code', sa.String(length=20), nullable=True),
    sa.Column('enterprise_fiscal_email', sa.String(length=100), nullable=True),
    sa.Column('enterprise_fiscal_phone', sa.String(length=20), nullable=True),
    sa.Column('enterprise_id_status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id_status'], ['status.id_status'], ),
    sa.PrimaryKeyConstraint('id_enterprise'),
    sa.UniqueConstraint('enterprise_name')
    )
    op.create_table('property',
    sa.Column('id_property', sa.Integer(), nullable=False),
    sa.Column('property_name', sa.String(length=100), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('property_id_status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id_enterprise'], ),
    sa.ForeignKeyConstraint(['property_id_status'], ['status.id_status'], ),
    sa.PrimaryKeyConstraint('id_property')
    )
    op.create_table('asset',
    sa.Column('id_asset', sa.Integer(), nullable=False),
    sa.Column('id_property', sa.Integer(), nullable=False),
    sa.Column('asset_number', sa.String(length=50), nullable=False),
    sa.Column('asset_name', sa.String(length=100), nullable=False),
    sa.Column('asset_front', sa.Float(), nullable=False),
    sa.Column('asset_depth', sa.Float(), nullable=False),
    sa.Column('asset_height', sa.Float(), nullable=False),
    sa.Column('asset_m2', sa.Float(), nullable=False),
    sa.Column('asset_m3', sa.Float(), nullable=False),
    sa.Column('asset_comments', sa.Text(), nullable=True),
    sa.Column('asset_photo1', sa.String(length=255), nullable=True),
    sa.Column('asset_photo2', sa.String(length=255), nullable=True),
    sa.Column('asset_photo3', sa.String(length=255), nullable=True),
    sa.Column('asset_photo4', sa.String(length=255), nullable=True),
    sa.Column('asset_photo5', sa.String(length=255), nullable=True),
    sa.Column('asset_type', sa.Integer(), nullable=False),
    sa.Column('asset_status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_status'], ['asset_status.id_status'], ),
    sa.ForeignKeyConstraint(['asset_type'], ['asset_type.id_asset_type'], ),
    sa.ForeignKeyConstraint(['id_property'], ['property.id_property'], ),
    sa.PrimaryKeyConstraint('id_asset')
    )
    op.create_table('reservation',
    sa.Column('id_reservation', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_asset', sa.Integer(), nullable=False),
    sa.Column('reservation_reservation_date', sa.DateTime(), nullable=True),
    sa.Column('reservation_deposit_amount', sa.Float(), nullable=False),
    sa.Column('reservation_expiration_date', sa.DateTime(), nullable=False),
    sa.Column('reservation_status', sa.String(length=50), nullable=False),
    sa.Column('reservation_total_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_asset'], ['asset.id_asset'], ),
    sa.ForeignKeyConstraint(['id_client'], ['client.id_client'], ),
    sa.PrimaryKeyConstraint('id_reservation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.drop_table('asset')
    op.drop_table('property')
    op.drop_table('enterprise')
    op.drop_table('user')
    op.drop_table('status')
    op.drop_table('reservation_status')
    op.drop_table('client')
    op.drop_table('asset_type')
    op.drop_table('asset_status')
    # ### end Alembic commands ###
