"""Creación inicial de la base de datos

Revision ID: 67afc2a8d368
Revises: 
Create Date: 2024-03-18 19:25:47.285338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67afc2a8d368'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datos_historicos',
    sa.Column('id_datos_historicos', sa.Integer(), nullable=False),
    sa.Column('ano_datos_historicos', sa.Integer(), nullable=True),
    sa.Column('sku_datos_historicos', sa.String(length=20), nullable=True),
    sa.Column('modelo_datos_historicos', sa.String(length=20), nullable=True),
    sa.Column('tipo_enser_datos_historicos', sa.String(length=50), nullable=True),
    sa.Column('clasificacion_enser_datos_historicos', sa.String(length=5), nullable=True),
    sa.Column('ventas_datos_historicos', sa.Float(), nullable=True),
    sa.Column('fecha_datos_historicos', sa.DateTime(timezone=True), nullable=True),
    sa.Column('semana_datos_historicos', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id_datos_historicos')
    )
    op.create_table('datos_ocupacion',
    sa.Column('id_datosocupacion', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=20), nullable=True),
    sa.Column('sku_tipo', sa.String(length=20), nullable=True),
    sa.Column('actual_factor_inventario', sa.Float(), nullable=True),
    sa.Column('actual_inventario', sa.Float(), nullable=True),
    sa.Column('actual_venta', sa.Float(), nullable=True),
    sa.Column('actual_area', sa.Float(), nullable=True),
    sa.Column('devoluciones_factor_inventario', sa.Float(), nullable=True),
    sa.Column('devoluciones_inventario', sa.Float(), nullable=True),
    sa.Column('devoluciones_area', sa.Float(), nullable=True),
    sa.Column('mensual_venta', sa.Float(), nullable=True),
    sa.Column('mensual_venta_devoluciones', sa.Float(), nullable=True),
    sa.Column('stagging_factor_inventario', sa.Float(), nullable=True),
    sa.Column('stagging_inventario', sa.Float(), nullable=True),
    sa.Column('stagging_area', sa.Float(), nullable=True),
    sa.Column('pronostico_diario', sa.Float(), nullable=True),
    sa.Column('pronostico_optimo', sa.Float(), nullable=True),
    sa.Column('area_pronostico_optimo', sa.Float(), nullable=True),
    sa.Column('inventario_seguridad', sa.Float(), nullable=True),
    sa.Column('punto_reorden', sa.Float(), nullable=True),
    sa.Column('cantidad_solicitar', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_datosocupacion')
    )
    op.create_table('enterprise',
    sa.Column('id_enterprise', sa.Integer(), nullable=False),
    sa.Column('enterprise_name', sa.String(length=80), nullable=False),
    sa.Column('rfc', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_enterprise'),
    sa.UniqueConstraint('enterprise_name')
    )
    op.create_table('factores',
    sa.Column('id_factores', sa.Integer(), nullable=False),
    sa.Column('nombre_factores', sa.String(length=50), nullable=True),
    sa.Column('sku_tipo', sa.String(length=20), nullable=True),
    sa.Column('valor_factores', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_factores')
    )
    op.create_table('forecast',
    sa.Column('id_forecast', sa.Integer(), nullable=False),
    sa.Column('ano_forecast', sa.Integer(), nullable=True),
    sa.Column('sku_forecats', sa.String(length=20), nullable=True),
    sa.Column('mes_forecast', sa.Integer(), nullable=True),
    sa.Column('ventas_forecast', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_forecast')
    )
    op.create_table('ocupacion',
    sa.Column('id_ocupacion', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('valor_real', sa.Float(), nullable=True),
    sa.Column('valor_proyectado', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_ocupacion')
    )
    op.create_table('pronostico_ocupacion_diario',
    sa.Column('id_pronostico_ocupacion_diario', sa.Integer(), nullable=False),
    sa.Column('dia_pronostico_ocupacion_diario', sa.String(length=20), nullable=True),
    sa.Column('valor_pronostico_diario', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_pronostico_ocupacion_diario')
    )
    op.create_table('pronostico_ocupacion_mensual',
    sa.Column('id_pronostico_ocupacion_mensual', sa.Integer(), nullable=False),
    sa.Column('dia_pronostico_ocupacion_mensual', sa.String(length=20), nullable=True),
    sa.Column('valor_pronostico_mensual', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_pronostico_ocupacion_mensual')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('surname', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('interior_number', sa.String(length=10), nullable=True),
    sa.Column('exterior_number', sa.String(length=10), nullable=True),
    sa.Column('municipality', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('profile', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('pronostico_ocupacion_mensual')
    op.drop_table('pronostico_ocupacion_diario')
    op.drop_table('ocupacion')
    op.drop_table('forecast')
    op.drop_table('factores')
    op.drop_table('enterprise')
    op.drop_table('datos_ocupacion')
    op.drop_table('datos_historicos')
    # ### end Alembic commands ###
