"""Create prices table

Revision ID: 70e61916780e
Revises: 5508a66f37a7
Create Date: 2024-08-24 13:37:49.619173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e61916780e'
down_revision = '5508a66f37a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price',
    sa.Column('id_price', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('rental_price', sa.Float(), nullable=False),
    sa.Column('deposit_type', sa.String(length=50), nullable=False),
    sa.Column('deposit_value', sa.Float(), nullable=False),
    sa.Column('deposit_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id_asset'], ),
    sa.PrimaryKeyConstraint('id_price')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('client_phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=False)

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reservation_amount_paid', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reservation_payment_status', sa.String(length=50), nullable=False))
        batch_op.alter_column('reservation_expiration_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('reservation_expiration_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('reservation_payment_status')
        batch_op.drop_column('reservation_amount_paid')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('client_phone',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    op.drop_table('price')
    # ### end Alembic commands ###
